sudo: false
language: ruby
cache: bundler
rvm:
  - 2.4.7
  - 2.5.7
  - 2.6.5
  - ruby-head
before_install:
  - sudo apt-get -y install libidn11-dev
  - gem update bundler
script: bundle exec rake spec
